# Generated by Django 4.1.2 on 2022-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=10)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Contect', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
